import Head from 'next/head';
import { MainDashboard } from '../components/MainDashboard';
import { Layout } from '../components/Layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <MainDashboard />
      </Layout>
    </div>
  );
}
