import Head from 'next/head';
import { MainDashboard } from '../components/MainDashboard';
import { Layout } from '../components/Layout';
import { useQuery } from '@apollo/client';
import { useAuth } from '@/lib/auth';
import { GET_USER_POOLS } from '@/lib/queries';
import { useRouter } from 'next/router';

export default function Home() {
  const { user } = useAuth();
  const router = useRouter();
  if (typeof window !== 'undefined') {
    if (!user) {
      router.push('/login');
    }
  }
  const { loading, data } = useQuery(GET_USER_POOLS(user?.id), {
    fetchPolicy: 'network-only',
  });

  if (loading)
    return (
      <Layout>
        <h1>Loading</h1>
      </Layout>
    );
  console.log(data);
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <MainDashboard pools={data?.user?.pools} />
      </Layout>
    </div>
  );
}
